# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := WebDriver
DEFS_Default := 

# Flags passed to all source files.
CFLAGS_Default := $(RPM_OPT_FLAGS)

# Flags passed to only C files.
CFLAGS_C_Default := $(RPM_OPT_FLAGS)

# Flags passed to only C++ files.
CFLAGS_CC_Default := $(RPM_OPT_FLAGS)

INCS_Default := -Iinc \
	-Isrc \
	-I/opt/qt4_nds/linux2_2/release/include

OBJS := $(obj).target/$(TARGET)/src/third_party/mongoose/mongoose.o \
	$(obj).target/$(TARGET)/src/chrome/test/webdriver/webdriver_server.o \
	$(obj).target/$(TARGET)/src/chrome/test/webdriver/webdriver_dispatch.o \
	$(obj).target/$(TARGET)/src/chrome/test/webdriver/commands/response.o \
	$(obj).target/$(TARGET)/src/chrome/test/webdriver/webdriver_error.o \
	$(obj).target/$(TARGET)/src/chrome/test/webdriver/commands/command.o \
	$(obj).target/$(TARGET)/src/chrome/test/webdriver/http_response.o \
	$(obj).target/$(TARGET)/src/chrome/test/webdriver/webdriver_automation.o \
	$(obj).target/$(TARGET)/src/chrome/test/webdriver/webdriver_session.o \
	$(obj).target/$(TARGET)/src/chrome/test/webdriver/webdriver_session_manager.o \
	$(obj).target/$(TARGET)/src/chrome/test/webdriver/webdriver_util.o \
	$(obj).target/$(TARGET)/src/chrome/test/automation/automation_json_requests.o \
	$(obj).target/$(TARGET)/src/chrome/test/webdriver/frame_path.o \
	$(obj).target/$(TARGET)/src/chrome/common/automation_id.o \
	$(obj).target/$(TARGET)/src/base/stringprintf.o \
	$(obj).target/$(TARGET)/src/base/string_number_conversions.o \
	$(obj).target/$(TARGET)/src/base/utf_string_conversions.o \
	$(obj).target/$(TARGET)/src/base/third_party/dmg_fp/g_fmt.o \
	$(obj).target/$(TARGET)/src/base/third_party/dmg_fp/dtoa.o \
	$(obj).target/$(TARGET)/src/base/utf_string_conversion_utils.o \
	$(obj).target/$(TARGET)/src/base/third_party/icu/icu_utf.o \
	$(obj).target/$(TARGET)/src/base/string16.o \
	$(obj).target/$(TARGET)/src/base/json/json_writer.o \
	$(obj).target/$(TARGET)/src/base/json/json_reader.o \
	$(obj).target/$(TARGET)/src/base/json/json_parser.o \
	$(obj).target/$(TARGET)/src/base/json/string_escape.o \
	$(obj).target/$(TARGET)/src/base/string_piece.o \
	$(obj).target/$(TARGET)/src/base/values.o \
	$(obj).target/$(TARGET)/src/chrome/test/webdriver/webdriver_element_id.o \
	$(obj).target/$(TARGET)/src/chrome/test/automation/value_conversion_traits.o \
	$(obj).target/$(TARGET)/src/chrome/test/webdriver/webdriver_basic_types.o \
	$(obj).target/$(TARGET)/src/chrome/test/webdriver/commands/create_session.o \
	$(obj).target/$(TARGET)/src/base/third_party/dynamic_annotations/dynamic_annotations.o \
	$(obj).target/$(TARGET)/src/base/task_runner.o \
	$(obj).target/$(TARGET)/src/base/threading/post_task_and_reply_impl.o \
	$(obj).target/$(TARGET)/src/base/memory/ref_counted.o \
	$(obj).target/$(TARGET)/src/base/callback_internal.o \
	$(obj).target/$(TARGET)/src/base/message_loop_proxy.o \
	$(obj).target/$(TARGET)/src/base/atomicops_internals_x86_gcc.o \
	$(obj).target/$(TARGET)/src/base/threading/thread_collision_warner.o \
	$(obj).target/$(TARGET)/src/base/threading/platform_thread_posix.o \
	$(obj).target/$(TARGET)/src/base/time.o \
	$(obj).target/$(TARGET)/src/base/third_party/nspr/prtime.o \
	$(obj).target/$(TARGET)/src/base/time_posix.o \
	$(obj).target/$(TARGET)/src/base/message_loop_proxy_impl.o \
	$(obj).target/$(TARGET)/src/base/threading/thread_restrictions.o \
	$(obj).target/$(TARGET)/src/base/lazy_instance.o \
	$(obj).target/$(TARGET)/src/base/threading/thread_local_posix.o \
	$(obj).target/$(TARGET)/src/base/tracked_objects.o \
	$(obj).target/$(TARGET)/src/base/synchronization/lock_impl_posix.o \
	$(obj).target/$(TARGET)/src/base/synchronization/lock.o \
	$(obj).target/$(TARGET)/src/base/message_loop.o \
	$(obj).target/$(TARGET)/src/base/run_loop.o \
	$(obj).target/$(TARGET)/src/base/pending_task.o \
	$(obj).target/$(TARGET)/src/base/metrics/statistics_recorder.o \
	$(obj).target/$(TARGET)/src/base/metrics/histogram.o \
	$(obj).target/$(TARGET)/src/base/memory/weak_ptr.o \
	$(obj).target/$(TARGET)/src/base/tracking_info.o \
	$(obj).target/$(TARGET)/src/base/thread_task_runner_handle.o \
	$(obj).target/$(TARGET)/src/base/message_pump_default.o \
	$(obj).target/$(TARGET)/src/base/pickle.o \
	$(obj).target/$(TARGET)/src/base/metrics/histogram_base.o \
	$(obj).target/$(TARGET)/src/base/metrics/sample_vector.o \
	$(obj).target/$(TARGET)/src/base/metrics/bucket_ranges.o \
	$(obj).target/$(TARGET)/src/base/location.o \
	$(obj).target/$(TARGET)/src/base/threading/thread_local_storage_posix.o \
	$(obj).target/$(TARGET)/src/base/profiler/tracked_time.o \
	$(obj).target/$(TARGET)/src/base/profiler/alternate_timer.o \
	$(obj).target/$(TARGET)/src/base/threading/thread_checker_impl.o \
	$(obj).target/$(TARGET)/src/base/synchronization/waitable_event_posix.o \
	$(obj).target/$(TARGET)/src/base/synchronization/condition_variable_posix.o \
	$(obj).target/$(TARGET)/src/base/message_pump.o \
	$(obj).target/$(TARGET)/src/base/metrics/histogram_samples.o \
	$(obj).target/$(TARGET)/src/base/threading/thread.o \
	$(obj).target/$(TARGET)/src/base/profiler/scoped_profile.o \
	$(obj).target/$(TARGET)/src/base/memory/singleton.o \
	$(obj).target/$(TARGET)/src/base/at_exit.o \
	$(obj).target/$(TARGET)/src/chrome/common/automation_constants.o \
	$(obj).target/$(TARGET)/src/chrome/test/webdriver/webdriver_capabilities_parser.o \
	$(obj).target/$(TARGET)/src/chrome/test/webdriver/webdriver_logging.o \
	$(obj).target/$(TARGET)/src/base/file_util.o \
	$(obj).target/$(TARGET)/src/base/logging.o \
	$(obj).target/$(TARGET)/src/base/file_util_posix.o \
	$(obj).target/$(TARGET)/src/base/file_path.o \
	$(obj).target/$(TARGET)/src/base/string_util.o \
	$(obj).target/$(TARGET)/src/base/platform_file_posix.o \
	$(obj).target/$(TARGET)/src/base/platform_file.o \
	$(obj).target/$(TARGET)/src/base/safe_strerror_posix.o \
	$(obj).target/$(TARGET)/src/base/sys_string_conversions_posix.o \
	$(obj).target/$(TARGET)/src/base/base64.o \
	$(obj).target/$(TARGET)/src/base/command_line.o \
	$(obj).target/$(TARGET)/src/third_party/modp_b64/modp_b64.o \
	$(obj).target/$(TARGET)/src/net/base/net_log.o \
	$(obj).target/$(TARGET)/src/net/base/file_stream.o \
	$(obj).target/$(TARGET)/src/net/base/net_errors.o \
	$(obj).target/$(TARGET)/src/net/base/net_errors_posix.o \
	$(obj).target/$(TARGET)/src/net/base/io_buffer.o \
	$(obj).target/$(TARGET)/src/net/base/file_stream_net_log_parameters.o \
	$(obj).target/$(TARGET)/src/net/base/file_stream_metrics.o \
	$(obj).target/$(TARGET)/src/net/base/file_stream_metrics_posix.o \
	$(obj).target/$(TARGET)/src/net/base/file_stream_posix.o \
	$(obj).target/$(TARGET)/src/base/threading/worker_pool.o \
	$(obj).target/$(TARGET)/src/base/threading/worker_pool_posix.o \
	$(obj).target/$(TARGET)/src/base/string_split.o \
	$(obj).target/$(TARGET)/src/chrome/test/webdriver/commands/webdriver_command.o \
	$(obj).target/$(TARGET)/src/chrome/test/webdriver/commands/session_with_id.o \
	$(obj).target/$(TARGET)/src/chrome/common/chrome_constants.o \
	$(obj).target/$(TARGET)/src/chrome/common/chrome_switches.o \
	$(obj).target/$(TARGET)/src/base/base_switches.o \
	$(obj).target/$(TARGET)/src/content/public/common/content_switches.o \
	$(obj).target/$(TARGET)/src/base/scoped_temp_dir.o \
	$(obj).target/$(TARGET)/src/chrome/test/webdriver/commands/url_command.o \
	$(obj).target/$(TARGET)/src/chrome/test/webdriver/commands/window_commands.o \
	$(obj).target/$(TARGET)/src/chrome/test/webdriver/commands/webelement_commands.o \
	$(obj).target/$(TARGET)/src/chrome/test/webdriver/commands/title_command.o \
	$(obj).target/$(TARGET)/src/chrome/test/webdriver/commands/target_locator_commands.o \
	$(obj).target/$(TARGET)/src/chrome/test/webdriver/commands/source_command.o \
	$(obj).target/$(TARGET)/src/chrome/test/webdriver/commands/set_timeout_commands.o \
	$(obj).target/$(TARGET)/src/chrome/test/webdriver/commands/screenshot_command.o \
	$(obj).target/$(TARGET)/src/chrome/test/webdriver/commands/navigate_commands.o \
	$(obj).target/$(TARGET)/src/chrome/test/webdriver/commands/mouse_commands.o \
	$(obj).target/$(TARGET)/src/chrome/test/webdriver/commands/log_command.o \
	$(obj).target/$(TARGET)/src/chrome/test/webdriver/commands/keys_command.o \
	$(obj).target/$(TARGET)/src/chrome/test/webdriver/commands/html5_storage_commands.o \
	$(obj).target/$(TARGET)/src/chrome/test/webdriver/commands/html5_location_commands.o \
	$(obj).target/$(TARGET)/src/chrome/test/webdriver/commands/find_element_commands.o \
	$(obj).target/$(TARGET)/src/chrome/test/webdriver/commands/file_upload_command.o \
	$(obj).target/$(TARGET)/src/chrome/test/webdriver/commands/execute_command.o \
	$(obj).target/$(TARGET)/src/chrome/test/webdriver/commands/execute_async_script_command.o \
	$(obj).target/$(TARGET)/src/chrome/test/webdriver/commands/cookie_commands.o \
	$(obj).target/$(TARGET)/src/chrome/test/webdriver/commands/chrome_commands.o \
	$(obj).target/$(TARGET)/src/chrome/test/webdriver/commands/browser_connection_commands.o \
	$(obj).target/$(TARGET)/src/chrome/test/webdriver/commands/appcache_status_command.o \
	$(obj).target/$(TARGET)/src/chrome/test/webdriver/commands/alert_commands.o \
	$(obj).target/$(TARGET)/src/chrome/test/webdriver/commands/sessions.o \
	$(obj).target/$(TARGET)/src/third_party/webdriver/atoms.o \
	$(obj).target/$(TARGET)/src/base/rand_util.o \
	$(obj).target/$(TARGET)/src/base/rand_util_posix.o \
	$(obj).target/$(TARGET)/src/chrome/common/zip.o \
	$(obj).target/$(TARGET)/src/chrome/common/zip_reader.o \
	$(obj).target/$(TARGET)/src/third_party/zlib/contrib/minizip/unzip.o \
	$(obj).target/$(TARGET)/src/chrome/common/zip_internal.o \
	$(obj).target/$(TARGET)/src/third_party/zlib/contrib/minizip/ioapi.o \
	$(obj).target/$(TARGET)/src/qtaskrunner.o \
	$(obj).target/$(TARGET)/src/chrome/common/chrome_version_info.o \
	$(obj).target/$(TARGET)/src/chrome/common/chrome_version_info_posix.o \
	$(obj).target/$(TARGET)/src/base/sys_info_posix.o \
	$(obj).target/$(TARGET)/src/base/sys_info_linux.o \
	$(obj).target/$(TARGET)/src/base/debug/alias.o \
	$(obj).target/$(TARGET)/src/base/debug/debugger.o \
	$(obj).target/$(TARGET)/src/base/debug/debugger_posix.o \
	$(obj).target/$(TARGET)/src/base/timer.o \
	$(obj).target/$(TARGET)/src/base/path_service.o \
	$(obj).target/$(TARGET)/src/base/base_paths.o \
	$(obj).target/$(TARGET)/src/base/base_paths_posix.o \
	$(obj).target/$(TARGET)/src/base/environment.o \
	$(obj).target/$(TARGET)/src/base/nix/xdg_util.o \
	$(obj).target/$(TARGET)/src/base/third_party/xdg_user_dirs/xdg_user_dir_lookup.o \
	$(obj).target/$(TARGET)/src/chrome/test/webdriver/webdriver_key_converter.o \
	$(obj).target/$(TARGET)/src/third_party/zlib/inflate.o \
	$(obj).target/$(TARGET)/src/third_party/zlib/zutil.o \
	$(obj).target/$(TARGET)/src/third_party/zlib/inftrees.o \
	$(obj).target/$(TARGET)/src/third_party/zlib/inffast.o \
	$(obj).target/$(TARGET)/src/third_party/zlib/infback.o \
	$(obj).target/$(TARGET)/src/third_party/zlib/crc32.o \
	$(obj).target/$(TARGET)/src/third_party/zlib/adler32.o \
	$(obj).target/$(TARGET)/src/chrome/test/webdriver/webdriver_switches.o \
	$(obj).target/$(TARGET)/src/qwebviewext.o \
	$(obj).target/$(TARGET)/src/moc_webdriver_automation.o \
	$(obj).target/$(TARGET)/src/moc_qtaskrunner.o \
	$(obj).target/$(TARGET)/src/moc_qwebviewext.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE)) $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE)) $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Default := 

LIBS := 

$(obj).target/libWebDriver.a: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/libWebDriver.a: LIBS := $(LIBS)
$(obj).target/libWebDriver.a: TOOLSET := $(TOOLSET)
$(obj).target/libWebDriver.a: $(OBJS) FORCE_DO_CMD
	$(call do_cmd,alink)

all_deps += $(obj).target/libWebDriver.a
# Add target alias
.PHONY: WebDriver
WebDriver: $(obj).target/libWebDriver.a

# Add target alias to "all" target.
.PHONY: all
all: WebDriver

