#ifndef WEBDRIVER_H
#define WEBDRIVER_H
/**
  * @mainpage This is autogenerated documentation for QtWebKitWebDriver. <br>
  * Public API for WD is in file inc/QtWebkitWebDriver.h
  */
/** @file
  * public API of QtWebkitWD
*/

#include <viewfactory.h>

#ifdef __cplusplus
extern "C"
{
#endif
/** @fn int main_server(int argc, char *argv[])
  * @brief starts WD server with parameters
  * @return EXIT_SUCCESS in case of successfull start of WD, errorcode otherwise
  **/
int main_server(int argc, char *argv[]);

#ifdef __cplusplus
}
#endif

/** @fn void registerView(std::string name)
  * @brief register View for testing
  * @param[in] name factory name for this class type
  **/
template <class T>
void registerView(std::string name)
{
    ViewFactory::GetInstance()->add<T>(name);
}

#endif // WEBDRIVER_H
