SOURCES += \
$$SRC_DIR/base/string16.cc \
$$SRC_DIR/base/time_posix.cc \
$$SRC_DIR/base/base_paths_android.cc \
$$SRC_DIR/base/debug/debugger_posix.cc \
$$SRC_DIR/base/file_util_android.cc \
$$SRC_DIR/base/file_util_posix.cc \
$$SRC_DIR/base/nix/xdg_util.cc \
$$SRC_DIR/base/platform_file_posix.cc \
$$SRC_DIR/base/rand_util_posix.cc \
$$SRC_DIR/base/safe_strerror_posix.cc \
$$SRC_DIR/base/synchronization/condition_variable_posix.cc \
$$SRC_DIR/base/synchronization/lock_impl_posix.cc \
$$SRC_DIR/base/synchronization/waitable_event_posix.cc \
$$SRC_DIR/base/sys_info_posix.cc \
$$SRC_DIR/base/sys_string_conversions_posix.cc \
$$SRC_DIR/base/threading/platform_thread_posix.cc \
$$SRC_DIR/base/threading/thread_local_posix.cc \
$$SRC_DIR/base/threading/thread_local_storage_posix.cc \
$$SRC_DIR/base/threading/worker_pool_posix.cc \
$$SRC_DIR/net/base/file_stream_metrics_posix.cc \
$$SRC_DIR/net/base/file_stream_posix.cc \
$$SRC_DIR/net/base/net_errors_posix.cc \
$$SRC_DIR/base/sys_info_linux.cc \
$$SRC_DIR/base/message_pump_android.cc \
$$SRC_DIR/base/os_compat_android.cc \
$$SRC_DIR/base/android/scoped_java_ref.cc \
$$SRC_DIR/base/android/path_utils.cc \
$$SRC_DIR/base/android/path_service_android.cc \
$$SRC_DIR/base/android/jni_string.cc \
$$SRC_DIR/base/android/jni_helper.cc \
$$SRC_DIR/base/android/jni_array.cc \
$$SRC_DIR/base/android/jni_android.cc
