
HEADERS += \
    $$INC_DIR/base/at_exit.h \
    $$INC_DIR/base/atomicops.h \
    $$INC_DIR/base/base64.h \
    $$INC_DIR/base/base_paths.h \
    $$INC_DIR/base/base_switches.h \
    $$INC_DIR/base/basictypes.h \
    $$INC_DIR/base/bind.h \
    $$INC_DIR/base/callback.h \
    $$INC_DIR/base/callback_internal.h \
    $$INC_DIR/base/command_line.h \
    $$INC_DIR/base/compiler_specific.h \
    $$INC_DIR/base/debug/alias.h \
    $$INC_DIR/base/debug/debugger.h \
    $$INC_DIR/base/debug/leak_annotations.h \
    $$INC_DIR/base/eintr_wrapper.h \
    $$INC_DIR/base/environment.h \
    $$INC_DIR/base/file_path.h \
    $$INC_DIR/base/file_util.h \
    $$INC_DIR/base/float_util.h \
    $$INC_DIR/base/format_macros.h \
    $$INC_DIR/base/hash_tables.h \
    $$INC_DIR/base/json/json_parser.h \
    $$INC_DIR/base/json/json_reader.h \
    $$INC_DIR/base/json/json_writer.h \
    $$INC_DIR/base/json/string_escape.h \
    $$INC_DIR/base/lazy_instance.h \
    $$INC_DIR/base/location.h \
    $$INC_DIR/base/logging.h \
    $$INC_DIR/base/mac/scoped_cftyperef.h \
    $$INC_DIR/base/mac/scoped_nsautorelease_pool.h \
    $$INC_DIR/base/memory/ref_counted.h \
    $$INC_DIR/base/memory/scoped_ptr.h \
    $$INC_DIR/base/memory/singleton.h \
    $$INC_DIR/base/memory/weak_ptr.h \
    $$INC_DIR/base/message_loop.h \
    $$INC_DIR/base/message_loop_proxy.h \
    $$INC_DIR/base/message_loop_proxy_impl.h \
    $$INC_DIR/base/message_pump_default.h \
    $$INC_DIR/base/message_pump.h \
    $$INC_DIR/base/message_pump_libevent.h \
    $$INC_DIR/base/message_pump_mac.h \
    $$INC_DIR/base/metrics/bucket_ranges.h \
    $$INC_DIR/base/metrics/histogram_base.h \
    $$INC_DIR/base/metrics/histogram.h \
    $$INC_DIR/base/metrics/histogram_samples.h \
    $$INC_DIR/base/metrics/sample_vector.h \
    $$INC_DIR/base/metrics/statistics_recorder.h \
    $$INC_DIR/base/path_service.h \
    $$INC_DIR/base/pending_task.h \
    $$INC_DIR/base/pickle.h \
    $$INC_DIR/base/platform_file.h \
    $$INC_DIR/base/port.h \
    $$INC_DIR/base/process_util.h \
    $$INC_DIR/base/profiler/alternate_timer.h \
    $$INC_DIR/base/profiler/scoped_profile.h \
    $$INC_DIR/base/profiler/tracked_time.h \
    $$INC_DIR/base/rand_util.h \
    $$INC_DIR/base/run_loop.h \
    $$INC_DIR/base/safe_strerror_posix.h \
    $$INC_DIR/base/scoped_temp_dir.h \
    $$INC_DIR/base/single_thread_task_runner.h \
    $$INC_DIR/base/stringize_macros.h \
    $$INC_DIR/base/string_number_conversions.h \
    $$INC_DIR/base/string_piece.h \
    $$INC_DIR/base/stringprintf.h \
    $$INC_DIR/base/string_split.h \
    $$INC_DIR/base/string_util.h \
    $$INC_DIR/base/synchronization/lock.h \
    $$INC_DIR/base/synchronization/lock_impl.h \
    $$INC_DIR/base/synchronization/waitable_event.h \
    $$INC_DIR/base/sys_string_conversions.h \
    $$INC_DIR/base/task_runner.h \
    $$INC_DIR/base/third_party/dmg_fp/dmg_fp.h \
    $$INC_DIR/base/third_party/dynamic_annotations/dynamic_annotations.h \
    $$INC_DIR/base/third_party/icu/icu_utf.h \
    $$INC_DIR/base/third_party/nspr/prtime.h \
    $$INC_DIR/base/threading/platform_thread.h \
    $$INC_DIR/base/threading/post_task_and_reply_impl.h \
    $$INC_DIR/base/threading/thread_checker_impl.h \
    $$INC_DIR/base/threading/thread_collision_warner.h \
    $$INC_DIR/base/threading/thread.h \
    $$INC_DIR/base/threading/thread_local.h \
    $$INC_DIR/base/threading/thread_restrictions.h \
    $$INC_DIR/base/threading/worker_pool.h \
    $$INC_DIR/base/thread_task_runner_handle.h \
    $$INC_DIR/base/time.h \
    $$INC_DIR/base/timer.h \
    $$INC_DIR/base/tracked_objects.h \
    $$INC_DIR/base/tracking_info.h \
    $$INC_DIR/base/utf_string_conversions.h \
    $$INC_DIR/base/utf_string_conversion_utils.h \
    $$INC_DIR/base/values.h \
    $$INC_DIR/build/build_config.h

SOURCES += \
    $$SRC_DIR/base/at_exit.cc \
    $$SRC_DIR/base/atomicops_internals_x86_gcc.cc \
    $$SRC_DIR/base/base64.cc \
    $$SRC_DIR/base/base_paths.cc \
    $$SRC_DIR/base/base_switches.cc \
    $$SRC_DIR/base/callback_internal.cc \
    $$SRC_DIR/base/command_line.cc \
    $$SRC_DIR/base/debug/alias.cc \
    $$SRC_DIR/base/debug/debugger.cc \
    $$SRC_DIR/base/environment.cc \
    $$SRC_DIR/base/file_path.cc \
    $$SRC_DIR/base/file_util.cc \
    $$SRC_DIR/base/json/json_parser.cc \
    $$SRC_DIR/base/json/json_reader.cc \
    $$SRC_DIR/base/json/json_writer.cc \
    $$SRC_DIR/base/json/string_escape.cc \
    $$SRC_DIR/base/lazy_instance.cc \
    $$SRC_DIR/base/location.cc \
    $$SRC_DIR/base/logging.cc \
    $$SRC_DIR/base/memory/ref_counted.cc \
    $$SRC_DIR/base/memory/singleton.cc \
    $$SRC_DIR/base/memory/weak_ptr.cc \
    $$SRC_DIR/base/message_loop.cc \
    $$SRC_DIR/base/message_loop_proxy.cc \
    $$SRC_DIR/base/message_loop_proxy_impl.cc \
    $$SRC_DIR/base/message_pump.cc \
    $$SRC_DIR/base/message_pump_default.cc \
    $$SRC_DIR/base/metrics/bucket_ranges.cc \
    $$SRC_DIR/base/metrics/histogram_base.cc \
    $$SRC_DIR/base/metrics/histogram.cc \
    $$SRC_DIR/base/metrics/histogram_samples.cc \
    $$SRC_DIR/base/metrics/sample_vector.cc \
    $$SRC_DIR/base/metrics/statistics_recorder.cc \
    $$SRC_DIR/base/path_service.cc \
    $$SRC_DIR/base/pending_task.cc \
    $$SRC_DIR/base/pickle.cc \
    $$SRC_DIR/base/platform_file.cc \
    $$SRC_DIR/base/profiler/alternate_timer.cc \
    $$SRC_DIR/base/profiler/scoped_profile.cc \
    $$SRC_DIR/base/profiler/tracked_time.cc \
    $$SRC_DIR/base/rand_util.cc \
    $$SRC_DIR/base/run_loop.cc \
    $$SRC_DIR/base/scoped_temp_dir.cc \
    $$SRC_DIR/base/string_number_conversions.cc \
    $$SRC_DIR/base/string_piece.cc \
    $$SRC_DIR/base/stringprintf.cc \
    $$SRC_DIR/base/string_split.cc \
    $$SRC_DIR/base/string_util.cc \
    $$SRC_DIR/base/synchronization/lock.cc \
    $$SRC_DIR/base/task_runner.cc \
    $$SRC_DIR/base/third_party/dmg_fp/dtoa.cc \
    $$SRC_DIR/base/third_party/dmg_fp/g_fmt.cc \
    $$SRC_DIR/base/third_party/dynamic_annotations/dynamic_annotations.c \
    $$SRC_DIR/base/third_party/icu/icu_utf.cc \
    $$SRC_DIR/base/third_party/nspr/prtime.cc \
    $$SRC_DIR/base/third_party/xdg_user_dirs/xdg_user_dir_lookup.cc \
    $$SRC_DIR/base/threading/post_task_and_reply_impl.cc \
    $$SRC_DIR/base/threading/thread.cc \
    $$SRC_DIR/base/threading/thread_checker_impl.cc \
    $$SRC_DIR/base/threading/thread_collision_warner.cc \
    $$SRC_DIR/base/threading/thread_restrictions.cc \
    $$SRC_DIR/base/threading/worker_pool.cc \
    $$SRC_DIR/base/thread_task_runner_handle.cc \
    $$SRC_DIR/base/time.cc \
    $$SRC_DIR/base/timer.cc \
    $$SRC_DIR/base/tracked_objects.cc \
    $$SRC_DIR/base/tracking_info.cc \
    $$SRC_DIR/base/utf_string_conversions.cc \
    $$SRC_DIR/base/utf_string_conversion_utils.cc \
    $$SRC_DIR/base/values.cc \
    $$SRC_DIR/net/base/file_stream.cc \
    $$SRC_DIR/net/base/file_stream_metrics.cc \
    $$SRC_DIR/net/base/file_stream_net_log_parameters.cc \
    $$SRC_DIR/net/base/io_buffer.cc \
    $$SRC_DIR/net/base/net_errors.cc \
    $$SRC_DIR/net/base/net_log.cc \
    $$SRC_DIR/third_party/modp_b64/modp_b64.cc
